import 'package:flutter/widgets.dart';

class AppStrings {
  static Map<String, Map<String, String>> values = {
    'en': {
      'appName': 'Sustainable Home',
      'home': 'Home',
      'learn': 'Learn',
      'quiz': 'Quiz',
      'challenges': 'Challenges',
      'profile': 'Profile',
      'learnSdgs': 'Learn SDGs',
      'learnSdgsSubtitle': 'Learn, apply, and track your impact',
      'interactiveQuiz': 'Interactive Quiz',
      'interactiveQuizSubtitle': 'Test your knowledge in short steps',
      'tipsChallenges': 'Tips & Challenges',
      'tipsChallengesSubtitle': 'Simple and realistic daily tasks',
      'newsStories': 'News & Stories',
      'newsStoriesSubtitle': 'Short stories and applicable ideas',
      'sdg11Title': 'SDG 11 Sustainable Cities',
      'sdg11Subtitle':
          'Make cities inclusive, safe, resilient, and sustainable.',
      'sdg12Title': 'SDG 12 Responsible Consumption',
      'sdg12Subtitle':
          'Ensure sustainable consumption and production patterns.',
      'learnMore': 'Learn More',
      'caseStudies': 'Case Studies',
      'watchVideo': 'Watch Video',
      'tipsTricks': 'Tips & Tricks',
      'quizMe': 'Quiz Me',
      'hint': 'Hint',
      'showAnswer': 'Show Answer',
      'nextQuestion': 'Next Question',
      'trackImpact': 'Track Your Impact',
      'co2Saved': 'CO₂ Saved',
      'wasteReduced': 'Waste Reduced',
      'challengesCompleted': 'Challenges Completed',
      'addAction': 'Add Action',
      'viewLeaderboard': 'View Leaderboard',
      'weeklyProgress': 'Weekly Progress',
      'tasks': 'tasks',
      'resetWeek': 'Reset Week',
      'quickActions': 'Quick actions',
      'actionTransport': 'Public transport',
      'actionRecycle': 'Recycle today',
      'actionTree': 'Plant a tree',
      'actionAdded': 'Added to your impact',
      'welcomeTitle': 'Welcome to your\nsustainability journey',
      'welcomeSubtitle': 'Learn, Act, Track Your Impact',
      'getStarted': 'Get Started',
      'skip': 'Skip',
      'next': 'Next',
      'startNow': 'Start now',
      'onboarding1Title': 'Small steps, big impact',
      'onboarding1Body': 'Learn simple habits that help the planet every day.',
      'onboarding2Title': 'Track your progress',
      'onboarding2Body':
          'See your CO₂ and waste reduction as you complete actions.',
      'onboarding3Title': 'Join challenges',
      'onboarding3Body': 'Weekly missions keep you motivated and consistent.',
      'login': 'Login',
      'signUp': 'Sign up',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'confirmPassword': 'Confirm password',
      'noAccount': "Don't have an account?",
      'haveAccount': 'Already have an account?',
      'requiredField': 'Required',
      'invalidEmail': 'Enter a valid email',
      'shortPassword': 'Password must be at least 6 characters',
      'passwordMismatch': 'Passwords do not match',
      'supabaseNotConfigured':
          'Supabase is not configured. Run the app with SUPABASE_URL and SUPABASE_ANON_KEY.',
      'loginFailed': 'Login failed. Check your email and password.',
      'networkError': 'Network error. Check your internet and SUPABASE_URL.',
      'ok': 'OK',
      'learnHeaderTitle': 'Explore SDGs',
      'learnHeaderSubtitle': 'Choose a goal to learn, then take small actions.',
      'searchSdgs': 'Search goals',
      'sdg11Chip': 'Cities',
      'sdg12Chip': 'Consumption',
      'favorites': 'Favorites',
      'clear': 'Clear',
      'noResults': 'No results',
      'news': 'News',
      'stories': 'Stories',
      'readMore': 'Read more',
      'searchStories': 'Search news and stories',
      'min': 'min',
      'watchLearn': 'Watch & Learn',
      'videoSubtitle': 'Educational videos to help the planet',
      'sortById': 'Sort: ID',
      'sortByTitle': 'Sort: Title',
      'notifications': 'Notifications',
      'markAllRead': 'Mark all read',
      'all': 'All',
      'unread': 'Unread',
      'noNotifications': 'No notifications yet',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'notifChallengeTitle': 'New weekly challenge',
      'notifChallengeBody': 'Complete 3 eco actions this week to level up.',
      'notifTipTitle': 'Pro tip',
      'notifTipBody': 'Use a reusable bottle to reduce plastic waste.',
      'notifNewsTitle': 'Green news',
      'notifNewsBody': 'A new recycling program has launched in your city.',
      'checkEmail': 'Account created. Check your email to confirm, then login.',
      'surveyTitle': 'Tell us more about you',
      'surveySubtitle': 'This helps us personalize your experience.',
      'surveyAge': 'Age (Years)',
      'surveyGender': 'Gender',
      'surveyEducation': 'Highest Level of Education',
      'surveyHousehold': 'Current Household Composition',
      'surveyResidenceType': 'Type of Residence',
      'surveyOwnership': 'Do you own or rent your home?',
      'surveyArea': 'How would you describe the area you live in?',
      'submit': 'Submit',
      'male': 'Male',
      'female': 'Female',
      'highSchool': 'High School or equivalent',
      'vocational': 'Vocational/Technical Training',
      'bachelor': 'Bachelor\'s Degree',
      'master': 'Master\'s Degree',
      'doctorate': 'Doctorate or higher',
      'liveAlone': 'Live alone',
      'livePartner': 'Live with partner/spouse',
      'livePartnerChildren': 'Live with partner/spouse and child(ren)',
      'liveFamilyFriends': 'Live with other family/friends',
      'other': 'Other',
      'apartment': 'Apartment/Condo',
      'singleFamily': 'Single-family house',
      'own': 'Own',
      'rent': 'Rent',
      'urban': 'Urban',
      'suburban': 'Suburban',
      'rural': 'Rural',
      'quizFinished': 'Quiz Finished!',
      'yourScore': 'Your Score',
      'wellDone': 'Well Done!',
      'keepLearning': 'Keep learning to help the planet.',
      'restartQuiz': 'Restart Quiz',
      'kg': 'kg',
      'badges': 'Badges',
      'contribution': 'Contribution',
      'trees': 'Trees',
      'ecoHero': 'Eco Hero',
      'level': 'Level',
      'supportChat': 'Support Chat',
      'supportChatSubtitle': 'Chat with our team for help',
      'leaderboard': 'Leaderboard',
      'points': 'points',
    },
    'ar': {
      'appName': 'البيت المستدام',
      'home': 'الرئيسية',
      'learn': 'تعلّم',
      'quiz': 'اختبار',
      'challenges': 'تحديات',
      'profile': 'الملف',
      'learnSdgs': 'تعلّم أهداف التنمية',
      'learnSdgsSubtitle': 'تعلم وطبق وتابع تأثيرك',
      'interactiveQuiz': 'اختبار تفاعلي',
      'interactiveQuizSubtitle': 'اختبر معلوماتك بخطوات بسيطة',
      'tipsChallenges': 'نصائح وتحديات',
      'tipsChallengesSubtitle': 'مهام يومية بسيطة وواقعية',
      'newsStories': 'أخبار وقصص',
      'newsStoriesSubtitle': 'قصص قصيرة وأفكار قابلة للتطبيق',
      'sdg11Title': 'الهدف 11: مدن ومجتمعات مستدامة',
      'sdg11Subtitle': 'اجعل المدن شاملة وآمنة وقادرة على الصمود ومستدامة.',
      'sdg12Title': 'الهدف 12: الاستهلاك والإنتاج المسؤولان',
      'sdg12Subtitle': 'ضمان أنماط استهلاك وإنتاج مستدامة.',
      'learnMore': 'اعرف أكثر',
      'caseStudies': 'دراسات حالة',
      'watchVideo': 'شاهد فيديو',
      'tipsTricks': 'نصائح وحيل',
      'quizMe': 'اختبرني',
      'hint': 'تلميح',
      'showAnswer': 'إظهار الإجابة',
      'nextQuestion': 'السؤال التالي',
      'trackImpact': 'تتبع تأثيرك',
      'co2Saved': 'CO₂ موفّر',
      'wasteReduced': 'نفايات أقل',
      'challengesCompleted': 'تحديات مكتملة',
      'addAction': 'إضافة إجراء',
      'viewLeaderboard': 'لوحة المتصدرين',
      'weeklyProgress': 'تقدّم الأسبوع',
      'tasks': 'مهمة',
      'resetWeek': 'إعادة تعيين الأسبوع',
      'quickActions': 'إجراءات سريعة',
      'actionTransport': 'مواصلات عامة',
      'actionRecycle': 'إعادة تدوير اليوم',
      'actionTree': 'ازرع شجرة',
      'actionAdded': 'تمت إضافة الإجراء لتأثيرك',
      'welcomeTitle': 'مرحباً بك في رحلة\nالاستدامة',
      'welcomeSubtitle': 'ابدأ اليوم بخطوات بسيطة',
      'getStarted': 'ابدأ',
      'skip': 'تخطي',
      'next': 'التالي',
      'startNow': 'ابدأ الآن',
      'onboarding1Title': 'خطوات صغيرة، أثر كبير',
      'onboarding1Body': 'تعلم عادات بسيطة تساعد الكوكب كل يوم.',
      'onboarding2Title': 'تابع تقدّمك',
      'onboarding2Body': 'راقب تقليل CO₂ والنفايات مع كل إجراء.',
      'onboarding3Title': 'شارك في التحديات',
      'onboarding3Body': 'مهام أسبوعية تحفّزك على الاستمرار.',
      'login': 'تسجيل الدخول',
      'signUp': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'name': 'الاسم',
      'confirmPassword': 'تأكيد كلمة المرور',
      'noAccount': 'ليس لديك حساب؟',
      'haveAccount': 'لديك حساب بالفعل؟',
      'requiredField': 'مطلوب',
      'invalidEmail': 'اكتب بريدًا صحيحًا',
      'shortPassword': 'كلمة المرور 6 أحرف على الأقل',
      'passwordMismatch': 'كلمتا المرور غير متطابقتين',
      'supabaseNotConfigured':
          'لم يتم تفعيل Supabase. شغّل التطبيق مع SUPABASE_URL و SUPABASE_ANON_KEY.',
      'loginFailed': 'فشل تسجيل الدخول. تأكد من البريد وكلمة المرور.',
      'networkError': 'مشكلة في الاتصال. تأكد من الإنترنت ورابط SUPABASE_URL.',
      'ok': 'حسنًا',
      'learnHeaderTitle': 'استكشف أهداف التنمية',
      'learnHeaderSubtitle': 'اختر هدفًا للتعلّم ثم جرّب خطوات بسيطة.',
      'searchSdgs': 'ابحث عن هدف',
      'sdg11Chip': 'المدن',
      'sdg12Chip': 'الاستهلاك',
      'favorites': 'المفضلة',
      'clear': 'مسح',
      'noResults': 'لا توجد نتائج',
      'news': 'أخبار',
      'stories': 'قصص',
      'readMore': 'اقرأ المزيد',
      'searchStories': 'ابحث في الأخبار والقصص',
      'min': 'د',
      'watchLearn': 'شاهد وتعلّم',
      'videoSubtitle': 'فيديوهات تعليمية لمساعدة الكوكب',
      'sortById': 'ترتيب: الرقم',
      'sortByTitle': 'ترتيب: العنوان',
      'notifications': 'الإشعارات',
      'markAllRead': 'تحديد الكل كمقروء',
      'all': 'الكل',
      'unread': 'غير مقروء',
      'noNotifications': 'لا توجد إشعارات حالياً',
      'today': 'اليوم',
      'yesterday': 'أمس',
      'notifChallengeTitle': 'تحدّي أسبوعي جديد',
      'notifChallengeBody': 'أكمل 3 إجراءات صديقة للبيئة هذا الأسبوع لتتقدم.',
      'notifTipTitle': 'نصيحة سريعة',
      'notifTipBody': 'استخدم زجاجة قابلة لإعادة الاستخدام لتقليل البلاستيك.',
      'notifNewsTitle': 'خبر أخضر',
      'notifNewsBody': 'تم إطلاق برنامج جديد لإعادة التدوير في مدينتك.',
      'checkEmail':
          'تم إنشاء الحساب. تحقق من بريدك لتأكيد الحساب ثم سجّل الدخول.',
      'surveyTitle': 'أخبرنا المزيد عنك',
      'surveySubtitle': 'يساعدنا هذا في تخصيص تجربتك.',
      'surveyAge': 'العمر (بالسنوات)',
      'surveyGender': 'الجنس',
      'surveyEducation': 'أعلى مستوى تعليمي',
      'surveyHousehold': 'تكوين الأسرة الحالي',
      'surveyResidenceType': 'نوع السكن',
      'surveyOwnership': 'هل تملك أم تستأجر منزلك؟',
      'surveyArea': 'بشكل عام، كيف تصف المنطقة التي تعيش فيها؟',
      'submit': 'إرسال',
      'male': 'ذكر',
      'female': 'أنثى',
      'highSchool': 'ثانوية عامة أو ما يعادلها',
      'vocational': 'تدريب مهني/تقني',
      'bachelor': 'درجة البكالوريوس',
      'master': 'درجة الماجستير',
      'doctorate': 'دكتوراه أو أعلى',
      'liveAlone': 'أعيش بمفردي',
      'livePartner': 'أعيش مع شريك/زوج',
      'livePartnerChildren': 'أعيش مع شريك/زوج وأطفال',
      'liveFamilyFriends': 'أعيش مع عائلة/أصدقاء آخرين',
      'other': 'أخرى',
      'apartment': 'شقة/كوندو',
      'singleFamily': 'منزل لعائلة واحدة',
      'own': 'تملك',
      'rent': 'إيجار',
      'urban': 'حضري (مدينة)',
      'suburban': 'ضواحي',
      'rural': 'ريفي',
      'quizFinished': 'انتهى الاختبار!',
      'yourScore': 'درجتك',
      'wellDone': 'أحسنت!',
      'keepLearning': 'استمر في التعلم لمساعدة الكوكب.',
      'restartQuiz': 'إعادة الاختبار',
      'kg': 'كجم',
      'badges': 'الأوسمة',
      'contribution': 'المساهمة',
      'trees': 'الأشجار',
      'ecoHero': 'بطل بيئي',
      'level': 'مستوى',
      'supportChat': 'دردشة الدعم',
      'supportChatSubtitle': 'تحدث مع فريقنا للحصول على المساعدة',
      'leaderboard': 'لوحة المتصدرين',
      'points': 'نقطة',
    },
  };

  static String get(String key, BuildContext context) {
    final lang = Localizations.localeOf(context).languageCode;
    return values[lang]?[key] ?? values['en']?[key] ?? key;
  }
}
